apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: k8s-monitor

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: saiaditya10/k8s-monitor-frontend:latest

          ports:
            - containerPort: 80